### ISSUE TITLE
블로그 제목.. "기술 블로"

### ISSUE THREAD

**Issue by misolab** [cheese10yun/cheese10yun.github.io#1]
의도적이신건지..."기술 블로" 
![screenshot](https://user-images.githubusercontent.com/12091580/50461601-da29f900-09c2-11e9-9690-823ee84fb32f.png)

좋은 정보 잘 보고 있습니다.

**Comment by cheese10yun** [comment]
@misolab 
이슈 감사합니다. 제가 오타가 너무 많은 편이라서 수정 작업해야겠네요. 
누군가에게 도움이 된다니 저도 기쁘네요.

**Comment by cheese10yun** [comment]
수정 완료했습니다. 감사합니다.
